global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['frontend:8501']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
