name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd nginx-image/
        docker build . --file Dockerfile --tag my-image-name:$(date -I)
        docker tag my-image-name:$(date -I) ${{ github.event.inputs.docker_username }}/my-image-name:latest
